# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zsh-tab-title = {
    pname = "zsh-tab-title";
    version = "3.4.0";
    src = fetchurl {
      url = "https://github.com/trystan2k/zsh-tab-title/blob/v3.4.0/zsh-tab-title.plugin.zsh";
      sha256 = "sha256-XKRLbay+c5e5UIUM96VNcnX0SOGDx1UOdxXjF4uaByQ=";
    };
  };
}
