# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  localsend = {
    pname = "localsend";
    version = "1.15.4";
    src = fetchurl {
      url = "https://github.com/localsend/localsend/releases/download/v1.15.4/LocalSend-1.15.4-linux-x86-64.deb";
      sha256 = "sha256-ptECW6t4CV7C89FuRovXRiRURjbGrDCD2YfUPTNsh4w=";
    };
  };
}
